name: Build and Upload CLI package

on:
  release:
    types: [created]

jobs:
  build-and-upload:
    name: Build and Upload
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Build Project
        run: cargo build --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: CLI
          path: target/release/cli
