name: Build and Upload CLI package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-upload:
    name: Build and Upload
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build project
      run: cargo  build --release --package cli

    - uses: actions/upload-artifact@v4
      with:
        name: CLI
        path: target/release/cli
